name: flutter_blank_project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_launcher_icons:
  flutter_inappwebview:
  responsive_framework:
    
  dio:
  url_launcher:
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets:
    #音频文件
    - assets/audios/
    #图片文件
    - assets/images/
    - assets/images/root/
    - assets/images/splash/
  # fonts:
    # - family: ShadowsIntoLight-Regular
    #   fonts:
    #     - asset: assets/ShadowsIntoLight-Regular.ttf
